# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59e6b6dcbbecbad1dbef8033820c72cbe5deb66f51f1c280e41d36859d1bd84938b9101e0b3e9ac0f1589208ea2ec2a4a8e6f8ade6e7a317fa93f00a772502a8

test:
  secret_key_base: 1e656e5433187d2a5cee0cf26130eb4530f273eb6f298727cbbf3f388eb1a2c5af6669694d7c58817a338b86c7b0e855a070a445d708afffbaba677a8a62b691

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
